version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
      - sudo apt-get install -y nodejs
      - npm install
  # pre_build:
  #   commands:
  #     - echo Entered the pre_build phase...
  #     - docker login –u User –p $LOGIN_PASSWORD
  # build:
  #   commands:
  #     - echo Entered the build phase...
  #     - echo Build started on `date`
  #     - mvn install
  # post_build:
  #   commands:
  #     - echo Entered the post_build phase...
  #     - echo Build completed on `date`
artifacts:
  files:
    - index.js